### ISSUE TITLE
Front Overlay

### ISSUE THREAD

**Issue by Deamoner** [lindelof/particles-bg#13]
Would love to use this as win or points animation overlay. Can we adopt to allow style transfer in props?

**Comment by lindelof** [comment]
Can you explain the effect you want to achieve, I think it should not be too difficult

**Comment by lindelof** [comment]
Oh of course you can set the style arbitrarily. you can set bg={{style}}

https://codesandbox.io/s/weathered-moon-3ugp3?file=/src/index.js
