### ISSUE TITLE
Particle.js Module parse failed: Unexpected token (13:5)

### ISSUE THREAD

**Issue by pprachit09** [lindelof/particles-bg#14]
I really like this package. But when I am trying to use it in react-nice-resume, I am getting below error.

Failed to compile.
```

./node_modules/proton-engine/src/core/Particle.js
Module parse failed: Unexpected token (13:5)
You may need an appropriate loader to handle this file type.
| export default class Particle {
|   /** @type string */
|   id = ''
|
|   /** @type {{p:Vector2D,v:Vector2D,a:Vector2D}} */
```

Any suggestions?

**Comment by HamidReazaNikoonia** [comment]
have any suggestion ?

**Comment by yusufdeepwork** [comment]
I have the same issue

**Comment by westn** [comment]
Same issue for me where I get:

```
ERROR in ./node_modules/proton-engine/src/core/Particle.js 13:5
Module parse failed: Unexpected token (13:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export default class Particle {
|   /** @type string */
>   id = ''
| 
|   /** @type {{p:Vector2D,v:Vector2D,a:Vector2D}} */
 @ ./node_modules/proton-engine/src/emitter/Emitter.js 3:0-40 9:37-45 274:42-50
 @ ./node_modules/proton-engine/src/index.js
 @ ./node_modules/particles-bg/dist/index.es.js
```

etc

**Comment by yusufdeepwork** [comment]
> Same issue for me where I get:
> 
> ```
> ERROR in ./node_modules/proton-engine/src/core/Particle.js 13:5
> Module parse failed: Unexpected token (13:5)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> | export default class Particle {
> |   /** @type string */
> >   id = ''
> | 
> |   /** @type {{p:Vector2D,v:Vector2D,a:Vector2D}} */
>  @ ./node_modules/proton-engine/src/emitter/Emitter.js 3:0-40 9:37-45 274:42-50
>  @ ./node_modules/proton-engine/src/index.js
>  @ ./node_modules/particles-bg/dist/index.es.js
> ```
> 
> etc

https://github.com/drawcall/Proton/issues/78

I have opened this issue because of It is related of Proton library

**Comment by yusufdeepwork** [comment]
I have come back proton-engine@4.1.5 and it works.
I guess Latest proton-engine version has a problem.
`npm i proton-engine@4.1.5`

**Comment by lindelof** [comment]
Yes it has been fixed, please verify
