### ISSUE TITLE
Add typescript declaration files

### ISSUE THREAD

**Issue by strdr4605** [lindelof/particles-bg#2]
As some apps are built nowadays with typescript may be better to create [Declaration Files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html).

**Comment by lindelof** [comment]
Yes, thanks for the reminder. You can help me with PR

**Comment by strdr4605** [comment]
@lindelof, will see when I have time. Probably this or next week I can create a PR or update this issue with some help on types. 
If no updates after next week probably you will take this issue or maybe someone else.

**Comment by lindelof** [comment]
thanks

**Comment by strdr4605** [comment]
@lindelof, usually the issues are closed after resolved. Maybe others will see it open and suggest something or contribute.
