### ISSUE TITLE
Adjust particles on window resize

### ISSUE THREAD

**Issue by strdr4605** [lindelof/particles-bg#3]
As shown in the example below. If initially, the window is small and I make it bigger, the particles don't cover all background space.

![image](https://user-images.githubusercontent.com/16056918/70033981-27422200-15b9-11ea-996b-2d459ea80afa.png)
-------
Probably it's not a big issue.

**Comment by lindelof** [comment]
For this example, you can change the position when you change the size again. Actually, it's just a circular animation

https://github.com/lindelof/particles-bg/blob/master/src/particles/Square.jsx
