### ISSUE TITLE
Running in typescript without custom config fails to build

### ISSUE THREAD

**Issue by ehud-am** [lindelof/particles-bg#5]
**Description**
First, a very cool dynamic background package. Thanks for sharing.
The config parameter is mandatory and thus the following resulted in build error:
~~~
<ParticlesBg num={80} type="cobweb" bg={true} />
~~~

The error is:
~~~
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<Props>): ParticlesBg', gave the following error.
    Property 'config' is missing in type '{ num: number; type: "cobweb"; bg: true; }' but required in type 'Readonly<Props>'.
  Overload 2 of 2, '(props: Props, context?: any): ParticlesBg', gave the following error.
    Property 'config' is missing in type '{ num: number; type: "cobweb"; bg: true; }' but required in type 'Readonly<Props>'.
~~~

**Potential fix**
Not sure if that works for any case, but at least for me editing the `index.d.ts` and changing line 55 to make the config parameter optional worked. 
~~~
  export interface Props {
...
    config?: ConfigProp;
...
~~~

**Comment by hcharley** [comment]
I'm having this problem as well. Will file a quick PR

**Comment by lindelof** [comment]
Please update to 2.4.2 The problem has been fixed

**Comment by hcharley** [comment]
🙏  Thank you @lindelof !
