### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientHeight' of null

### ISSUE THREAD

**Issue by eugle** [lindelof/particles-bg#7]
![image](https://user-images.githubusercontent.com/24447931/71442912-08135c00-2743-11ea-915a-a41ec736146d.png)

**Comment by lindelof** [comment]
I guess your react version is not 16+, because I used the ref fetch method of react16

**Comment by eugle** [comment]
@lindelof 
![image](https://user-images.githubusercontent.com/24447931/71559150-b990f500-2a95-11ea-8aad-bccb8ed0ce1a.png)

**Comment by eugle** [comment]
When logged in, this error will appear, I wonder, should route jump, the program did not stop caused

**Comment by nvhoanganh** [comment]
I have the same issue

**Comment by lkovesdi** [comment]
Same problem, let me know if someone has updates one this!

**Comment by kushhingol** [comment]
Facing the same problem, i think we need to add a canvas clientHeight null check

**Comment by RyanRoll** [comment]
Could someone help review my PR to fix this issue bc the owner is not online?

**Comment by codegrau** [comment]
Same problem - would be nice if @lindelof or someone else could help here.

**Comment by AlexanderStewart** [comment]
I have the same issue.

**Comment by caoyuyu1213** [comment]
各位大哥有啥解决方案了没啊

**Comment by lindelof** [comment]
Oh, the problem has been fixed. You can download the latest particles-bg version. Thanks @kushhingol your solution is correct.

**Comment by lindelof** [comment]
> When logged in, this error will appear, I wonder, should route jump, the program did not stop caused

The problem has been fixed, you can download the latest version and use it.
