### ISSUE TITLE
SSR support increase

### ISSUE THREAD

**Issue by eugle** [lindelof/particles-bg#9]
I enabled SSR, whether can ban/SRC/particles/Canvas JSX window.addEventListener running on the server?

So you can support SSR, thanks

**Comment by lindelof** [comment]
I have no energy to write the ssr part for now, maybe you can achieve it

**Comment by eugle** [comment]
I mean, not in the server environment, just no error, say, whether there is a window or not

typeof window !== 'undefined' && window.addEventListener...

Is it possible to implement it quickly

**Comment by eugle** [comment]
@lindelof
